name: Build Android APK

on:
  push:
      branches: [ "test" ]
  pull_request:
      branches: [ "test" ]
      
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3.8.1
        with:
          node-version: 14

      - name: Install dependencies
        run: yarn install

      - name: React Native Android Build APK
        uses: realabbas/Github-Actions-React-Native@v1.1.2

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.3
